### ISSUE TITLE
请问大佬，nextjs 和nuxt.js 应该学哪个？

### ISSUE THREAD

**Issue by 24** [lqsong/lqsblog-frontend-nextjs#1]
我看大佬写了 nuxt.js  还有next.js 两个版本。真强大。。。。。

求大神分析下，应该按照哪个学？ 有什么性能，前途等区别？ 哪个写着爽歪歪？

**Comment by lqsong** [comment]
各有优点，这个要结合自己的实际情况进行选择学习，至于他们的性能区别，网上很多资料。本人只是一个前端小将。
